/* File: AU_FightSong.h
 * Author: Benjamin Cyr
 * Date: April 15, 2017
 */
 
 #ifndef _AU_FIGHTSONG_H_
 #define _AU_FIGHTSONG_H_
 
 #include "notes.h"
 
 #define AU_FIGHTSONG_BPM 300
 #define AU_FIGHTSONG_SIZE 73
 
 #define AU_FIGHTSONG {\
	  C4(WHOLE_NOTE),\
		A4(HALF_NOTE),\
		G4(HALF_NOTE),\
		F4(QUARTER_NOTE),\
		F4(HALF_NOTE),\
		D4(QUARTER_NOTE),\
		C4(DOTTED_HALF_NOTE),\
		REST(QUARTER_NOTE),\
		E4(QUARTER_NOTE),\
		E4(HALF_NOTE),\
		F4(QUARTER_NOTE),\
		G4(HALF_NOTE),\
		C4(HALF_NOTE),\
		F4(QUARTER_NOTE),\
		F4(HALF_NOTE),\
		G4(QUARTER_NOTE),\
		A4(DOTTED_HALF_NOTE),\
		REST(QUARTER_NOTE),\
		C4(WHOLE_NOTE),\
		A4(HALF_NOTE),\
		G4(HALF_NOTE),\
		F4(QUARTER_NOTE),\
		F4(HALF_NOTE),\
		D4(QUARTER_NOTE),\
		C4(DOTTED_HALF_NOTE),\
		REST(QUARTER_NOTE),\
		E4(QUARTER_NOTE),\
		Eb4(HALF_NOTE),\
		E4(QUARTER_NOTE),\
		F4(QUARTER_NOTE),\
		E4(QUARTER_NOTE),\
		D4(HALF_NOTE),\
		G4(QUARTER_NOTE),\
		REST(QUARTER_NOTE),\
		C5(HALF_NOTE),\
		C5(HALF_NOTE),\
		C5(HALF_NOTE),\
		C5(DOTTED_HALF_NOTE),\
		Bb4(QUARTER_NOTE),\
		A4(HALF_NOTE),\
		G4(HALF_NOTE),\
		F4(QUARTER_NOTE),\
		F4(HALF_NOTE),\
		G4(QUARTER_NOTE),\
		A4(DOTTED_HALF_NOTE),\
		REST(QUARTER_NOTE),\
		D5(QUARTER_NOTE),\
		D5(QUARTER_NOTE),\
		C5(HALF_NOTE),\
		D5(QUARTER_NOTE),\
		D5(QUARTER_NOTE),\
		C5(HALF_NOTE),\
		Bb4(QUARTER_NOTE),\
		Bb4(HALF_NOTE),\
		A4(QUARTER_NOTE),\
		G4(QUARTER_NOTE),\
		REST(QUARTER_NOTE),\
		C5(QUARTER_NOTE),\
		REST(QUARTER_NOTE),\
		C4(WHOLE_NOTE),\
		A4(HALF_NOTE),\
		G4(HALF_NOTE),\
		F4(HALF_NOTE),\
		G4(HALF_NOTE),\
		A4(HALF_NOTE),\
		D5(HALF_NOTE),\
		C5(QUARTER_NOTE),\
		B4(HALF_NOTE),\
		C5(QUARTER_NOTE),\
		A4(HALF_NOTE),\
		G4(HALF_NOTE),\
		F4(WHOLE_NOTE + QUARTER_NOTE),\
		REST(DOTTED_HALF_NOTE)\
	};		
 
 #endif
