/* File: ZeldasLullaby.h
 * Author: Benjamin Cyr
 * Date: April 15, 2017
 */
 
 #ifndef _ZELDASLULLABY_H_
 #define _ZELDASLULLABY_H_
 
 #include "notes.h"
 
 #define SONG_SIZE 63
 
 #define SONG {\
	  B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
	  A4(HALF_NOTE),\
		\
		G4(EIGHTH_NOTE),\
		A4(EIGHTH_NOTE),\
	  B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
	  A4(DOTTED_HALF_NOTE),\
	  \
	  B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
	  A5(HALF_NOTE),\
	  G5(QUARTER_NOTE),\
	  D5(HALF_NOTE),\
	  C5(EIGHTH_NOTE),\
		B4(EIGHTH_NOTE),\
	  A4(DOTTED_HALF_NOTE),\
	  \
	  B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
	  A4(HALF_NOTE),\
		\
		G4(EIGHTH_NOTE),\
		A4(EIGHTH_NOTE),\
		B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
	  A4(DOTTED_HALF_NOTE),\
		\
		B4(HALF_NOTE),\
	  D5(QUARTER_NOTE),\
		A5(HALF_NOTE),\
		G5(QUARTER_NOTE),\
		D6(DOTTED_HALF_NOTE + HALF_NOTE),\
		\
		G5(SIXTEENTH_NOTE),\
		A5(SIXTEENTH_NOTE),\
		B5(SIXTEENTH_NOTE),\
		C6(SIXTEENTH_NOTE),\
		D6(HALF_NOTE),\
		C6(EIGHTH_NOTE),\
		B5(EIGHTH_NOTE),\
		C6(EIGHTH_NOTE),\
		B5(EIGHTH_NOTE),\
		G5(HALF_NOTE),\
		\
		C6(HALF_NOTE),\
		B5(EIGHTH_NOTE),\
		A5(EIGHTH_NOTE),\
		B5(EIGHTH_NOTE),\
		A5(EIGHTH_NOTE),\
		E5(HALF_NOTE),\
		\
		D6(HALF_NOTE),\
		C6(EIGHTH_NOTE),\
		B5(EIGHTH_NOTE),\
		C6(EIGHTH_NOTE),\
		B5(EIGHTH_NOTE),\
		G5(QUARTER_NOTE),\
		C6(QUARTER_NOTE),\
		G6(DOTTED_HALF_NOTE),\
		\
		D4(EIGHTH_NOTE),\
		A4(EIGHTH_NOTE),\
		C5(EIGHTH_NOTE),\
		F5(EIGHTH_NOTE),\
		A5(EIGHTH_NOTE),\
		C6(EIGHTH_NOTE),\
		G4(SIXTEENTH_NOTE),\
		D5(SIXTEENTH_NOTE),\
		B5(SIXTEENTH_NOTE),\
		G6(DOTTED_HALF_NOTE)\
	};		
 
 #endif
